name: Test Actions
run-name: ${{ github.actor }} is testing
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    name: Run test
    strategy:
      matrix:
        versions: [21, 22, 23]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
     - uses: actions/checkout@v3
     - name: Setup golang
       uses: actions/setup-go@v3
       with:
        go-version: "stable"
    - name: Verify depends
      run: go mod verify
    - name: Run tests
      run: go run -v ./...


